/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.proyecto;
import java.awt.Color;
import java.awt.Container;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author Chicago
 */
public class RegistroUsuario extends javax.swing.JFrame {
    String sexo="";

    /** Creates new form RegistroUsuario */
    public RegistroUsuario() {
        initComponents();
        
        setTitle("Crear cuenta");
        setSize(956,550);
        setLocationRelativeTo(null);
        setResizable(false);
        
                LineBorder linea = new LineBorder(Color.white,8,true);
                
                txtUsuario.setBorder(linea);
                txtPass.setBorder(linea);
                txtAge.setBorder(linea);
                
       jPanel1.setBackground(new Color(169,204,227));
       
    }
    
 
    
    
    
    

   
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        mujer = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        hombre = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registrar_Usuario/Bienvenido.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 180, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nueva carpeta/Welcome back plese enter your details.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 200, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registrar_Usuario/Sexo.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registrar_Usuario/Nombre.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registrar_Usuario/Contraseña.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registrar_Usuario/Edad.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgeKeyTyped(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 230, 30));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 230, 30));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 230, 30));

        mujer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mujerStateChanged(evt);
            }
        });
        jPanel1.add(mujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 30, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registrar_Usuario/Mujer.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, 30));

        hombre.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hombreStateChanged(evt);
            }
        });
        jPanel1.add(hombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 30, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registrar_Usuario/Hombre.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nueva carpeta/Register.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, 20));

        jButton1.setBackground(new java.awt.Color(110, 39, 163));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 230, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nueva carpeta/IMGBIN_hamburger-cheeseburger-veggie-burger-fast-food-bobs-burgers-png_HaVwgkPX 2.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 160, 120));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nueva carpeta/Bitmap.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -20, 320, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     
       
       
       
         String usuario = txtUsuario.getText().trim();
        String age = txtAge.getText().trim();

        String contra= String.valueOf(txtPass.getPassword());

        //campos vacios
        if ((usuario.equals("")) || (contra.equals(""))|| (age.equals("")) ||sexo.equals("")  ) {

            JOptionPane.showMessageDialog(null, "Campos vacios");
           
            //validar usuario
        } else {
            
        
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/login", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into usuario values(?,?,?,?,?)");
            
            pst.setString(1, "0");
            pst.setString(2, txtUsuario.getText().trim().toLowerCase());
            pst.setString(3, contra.toLowerCase());
            pst.setString(4, txtAge.getText());
            pst.setString(5, sexo);
            
            pst.executeUpdate();
           
        
        }catch (Exception e){
            
        }     

        this.setVisible(false);
        
         Login lg = new Login();
            lg.setVisible(true);
            
            
        }

            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hombreStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hombreStateChanged
          if(hombre.isSelected()==true){
        sexo="hombre";
        }
        
        if(mujer.isSelected()==true){
        sexo="mujer";
        }
        
    }//GEN-LAST:event_hombreStateChanged

    private void mujerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mujerStateChanged
   if(mujer.isSelected()==true){
        sexo="mujer";
        }
        
        if(hombre.isSelected()==true){
        sexo="hombre";
        }
        
    }//GEN-LAST:event_mujerStateChanged

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed

// TODO add your handling code here:
    }//GEN-LAST:event_txtAgeKeyPressed

    private void txtAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyTyped
char a =evt.getKeyChar();
if (( ((int)a>=0 && (int)a<=47))||((int)a>=58 && (int)a<=255)){
evt.consume();
}

    }//GEN-LAST:event_txtAgeKeyTyped

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox hombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox mujer;
    private javax.swing.JTextField txtAge;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
