/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto;

import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Chicago
 */
public class RegistroLogin extends javax.swing.JFrame {

    String tipo;

    /**
     * Creates new form NewJFrame
     */
    public RegistroLogin() {
        initComponents();
        setSize(1070, 790);
        setResizable(false);
        setLocationRelativeTo(null);
        Container fondo = getContentPane();
        fondo.setBackground(new Color(255, 255, 255));

        LineBorder linea = new LineBorder(new Color(225, 225, 225), 1, true);
        txt_Id.setBorder(linea);
        txtUsuario.setBorder(linea);
        txt_Cantidad.setBorder(linea);
        txtUsuario.setBorder(linea);
        txtDireccion.setBorder(linea);
        btnIngresar.setBackground(new Color(234, 69, 76));
        btnIngresar.setForeground(new Color(255, 255, 255));

    }

    public void getLimpiarDatos() {
        txt_Cantidad.setText("");
        txtUsuario.setText("");
        txtDireccion.setText("");
        taDescripcion.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        comboTipoH = new javax.swing.JComboBox<>();
        comboDescuento = new javax.swing.JComboBox<>();
        txt_Cantidad = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Productos/Ingresa tu Pedido.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galeria/home.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ingresa tu id.png"))); // NOI18N

        txt_Id.setPreferredSize(new java.awt.Dimension(64, 37));
        txt_Id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_IdMousePressed(evt);
            }
        });
        txt_Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IdKeyTyped(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setText("Actualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        comboTipoH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hamburguesa Vegetariana $75", "Hamburguesa Hawaiana $50", "Hamburguesa De Ternera $135", "Hamburguesa De Pescado $120" }));
        comboTipoH.setMinimumSize(new java.awt.Dimension(72, 35));
        comboTipoH.setPreferredSize(new java.awt.Dimension(72, 37));
        comboTipoH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoHActionPerformed(evt);
            }
        });

        comboDescuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Precion Normal", "30%  Por Cumpleaños", "10%  Por Cupon" }));
        comboDescuento.setMinimumSize(new java.awt.Dimension(72, 35));
        comboDescuento.setPreferredSize(new java.awt.Dimension(72, 37));

        txt_Cantidad.setPreferredSize(new java.awt.Dimension(64, 37));

        txtUsuario.setPreferredSize(new java.awt.Dimension(64, 37));

        txtDireccion.setPreferredSize(new java.awt.Dimension(64, 37));

        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        taDescripcion.setBorder(null);
        jScrollPane1.setViewportView(taDescripcion);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registrar Pedido/Tipo de hamburguesas.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cuantas hamburguesas.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registrar Pedido/Descuento.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registrar Pedido/Nombre.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registrar Pedido/Dirección.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registrar Pedido/Descripción.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(38, 38, 38)
                                .addComponent(jButton4)
                                .addGap(38, 38, 38)
                                .addComponent(jButton5)
                                .addContainerGap())
                            .addComponent(txt_Id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboTipoH, 0, 321, Short.MAX_VALUE)
                            .addComponent(txt_Cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboDescuento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboTipoH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56))
                                    .addComponent(comboDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)))
                        .addGap(28, 28, 28)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Productos/social media.png"))); // NOI18N

        btnIngresar.setBackground(new java.awt.Color(255, 51, 51));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorderPainted(false);
        btnIngresar.setMaximumSize(new java.awt.Dimension(76, 40));
        btnIngresar.setMinimumSize(new java.awt.Dimension(76, 37));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(228, 228, 228))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(199, 199, 199))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 710, 690));

        jPanel4.setBackground(new java.awt.Color(6, 166, 126));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Productos/Ellipse 5.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Productos/Bienvenido.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Productos/Ellipse 2.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Productos/Rectangle 4.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Productos/Polygon 1.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Productos/Polygon 2.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        tipo = comboTipoH.getSelectedItem().toString();
        String n_Hamburguesa = String.valueOf(txt_Cantidad);

        String usuario = txtUsuario.getText().trim().toLowerCase();
        String direccion = txtDireccion.getText().trim();
        String descripcion = taDescripcion.getText().trim();
        //campos vacios
        if (usuario.equals("") || direccion.equals("") || descripcion.equals("") || n_Hamburguesa.equals("")) {

            JOptionPane.showMessageDialog(null, "Campos vacios");

            //validar usuario
        } else {

            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/login", "root", "");
                PreparedStatement pst = cn.prepareStatement("insert into registroinvitado values(?,?,?,?,?,?)");

                pst.setString(1, "0");
                pst.setString(2, String.valueOf(tipo).trim());
                pst.setString(3, txt_Cantidad.getText().trim());

                pst.setString(4, txtUsuario.getText().trim());
                pst.setString(5, txtDireccion.getText().trim());
                pst.setString(6, taDescripcion.getText().trim());

                pst.executeUpdate();

            } catch (Exception e) {

            }

            this.setVisible(true);
            int c_Hamburguesa = Integer.parseInt(txt_Cantidad.getText());
            double total;
            double total2 = 0;

            if (comboDescuento.getSelectedIndex() == 0) {
                if (tipo == "Hamburguesa Vegetariana $75") {
                    total = 75 * c_Hamburguesa;
                    JOptionPane.showMessageDialog(null, "Tu compra de una Hamburguesa Vegetariana es de:" + total);
                    getLimpiarDatos();

                } else if (tipo == "Hamburguesa Hawaiana $50") {
                    total = 50 * c_Hamburguesa;
                    JOptionPane.showMessageDialog(null, "Tu compra de una Hamburguesa Hawaiana es de:" + total);
                    getLimpiarDatos();
                }
                if (tipo == "Hamburguesa De Ternera $135") {
                    total = 135 * c_Hamburguesa;
                    JOptionPane.showMessageDialog(null, "Tu compra de una Hamburguesa De Ternera  es de:" + total);
                    getLimpiarDatos();
                } else if (tipo == "Hamburguesa De Pescado $120") {
                    total = 120 * c_Hamburguesa;
                    JOptionPane.showMessageDialog(null, "Tu compra de una Hamburguesa De Pescado es de:" + total);
                    getLimpiarDatos();
                }

                //Descuento por cumpleaños
            } else if (comboDescuento.getSelectedIndex() == 1) {

                if (tipo == "Hamburguesa Vegetariana $75") {
                    total = 75 * c_Hamburguesa;
                    total2 += total * 0.30;
                    total2 = total - total2;
                    JOptionPane.showMessageDialog(null, "Tu compra de una Hamburguesa Vegetariana es de:" + total2);
                    getLimpiarDatos();

                } else if (tipo == "Hamburguesa Hawaiana $50") {
                    total = 50 * c_Hamburguesa;
                    total2 += total * 0.30;
                    total2 = total - total2;
                    JOptionPane.showMessageDialog(null, "Tu compra de una Hamburguesa Hawaiana es de:" + total2);
                    getLimpiarDatos();
                }
                if (tipo == "Hamburguesa De Ternera $135") {
                    total = 135 * c_Hamburguesa;
                    total2 += total * 0.30;
                    total2 = total - total2;
                    JOptionPane.showMessageDialog(null, "Tu compra de una Hamburguesa De Ternera  es de:" + total2);
                    getLimpiarDatos();
                } else if (tipo == "Hamburguesa De Pescado $120") {
                    total = 120 * c_Hamburguesa;
                    total2 += total * 0.30;
                    total2 = total - total2;
                    JOptionPane.showMessageDialog(null, "Tu compra de una Hamburguesa De Pescado es de:" + total2);
                    getLimpiarDatos();
                }

            } else if (comboDescuento.getSelectedIndex() == 2) {

                if (tipo == "Hamburguesa Vegetariana $75") {
                    total = 75 * c_Hamburguesa;
                    total2 += total * 0.10;
                    total2 = total - total2;
                    JOptionPane.showMessageDialog(null, "Tu compra de una Hamburguesa Vegetariana es de:" + total2);
                    getLimpiarDatos();

                } else if (tipo == "Hamburguesa Hawaiana $50") {
                    total = 50 * c_Hamburguesa;
                    total2 += total * 0.10;
                    total2 = total - total2;
                    JOptionPane.showMessageDialog(null, "Tu compra de una Hamburguesa Hawaiana es de:" + total2);
                    getLimpiarDatos();
                }
                if (tipo == "Hamburguesa De Ternera $135") {
                    total = 135 * c_Hamburguesa;
                    total2 += total * 0.10;
                    total2 = total - total2;
                    JOptionPane.showMessageDialog(null, "Tu compra de una Hamburguesa De Ternera  es de:" + total2);
                    getLimpiarDatos();
                } else if (tipo == "Hamburguesa De Pescado $120") {
                    total = 120 * c_Hamburguesa;
                    total2 += total * 0.10;
                    total2 = total - total2;
                    JOptionPane.showMessageDialog(null, "Tu compra de una Hamburguesa De Pescado es de:" + total2);
                    getLimpiarDatos();
                }

            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txt_IdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_IdMousePressed

             // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
Menu menu = new Menu();
menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_IdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IdKeyTyped
char a =evt.getKeyChar();
if (( ((int)a>=0 && (int)a<=47))||((int)a>=58 && (int)a<=255)){
evt.consume();
}

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 try {
                String ID = txt_Id.getText().trim();
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/login", "root", "");
                PreparedStatement pst = cn.prepareStatement("update registroinvitado set Cantidad_Hamburguesa=?,Nombre=?,Direccion=?,Descripcion=? where id=" + ID);
                pst.setString(1, txt_Cantidad.getText().trim());
                pst.setString(2, txtUsuario.getText().trim());
                pst.setString(3, txtDireccion.getText().trim());
                pst.setString(4, taDescripcion.getText().trim());
                txt_Id.setText("");
                txt_Cantidad.setText("");
                txtUsuario.setText("");
                txtDireccion.setText("");
                taDescripcion.setText("");

                pst.executeUpdate();
            } catch (Exception e) {
            }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/login", "root", "");
                PreparedStatement pst = cn.prepareStatement("delete from registroinvitado where id=?");
                pst.setString(1, txt_Id.getText().trim());
                pst.executeUpdate();
                txt_Id.setText("");
                txt_Cantidad.setText("");
                txtUsuario.setText("");
                txtDireccion.setText("");
                taDescripcion.setText("");

            } catch (Exception e) {
            }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/login", "root", "");
                PreparedStatement pst = cn.prepareStatement("select * from registroinvitado where id = ?");
                pst.setString(1, txt_Id.getText().trim());

                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    txt_Cantidad.setText(rs.getString("Cantidad_Hamburguesa"));
                    txtUsuario.setText(rs.getString("Nombre"));
                    txtDireccion.setText(rs.getString("Direccion"));
                    taDescripcion.setText(rs.getString("Descripcion"));

                } else {
                    JOptionPane.showMessageDialog(null, "Invalido");
                }

            } catch (Exception e) {

            }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboTipoHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> comboDescuento;
    private javax.swing.JComboBox<String> comboTipoH;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txt_Cantidad;
    private javax.swing.JTextField txt_Id;
    // End of variables declaration//GEN-END:variables

}
